<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Template;
use App\Models\PlanCuentas;



class PlanCuentasSeeder extends Seeder
{
    public function run()
    {

        $template = Template::firstOrCreate(
            ['name' => 'Cuentas Supersias'],
            ['description' => 'Las cuentas de supersias son las cuentas que se utilizan para llevar el registro de las transacciones financieras de una empresa.']
        );

        $cuentas = [
            //Pag1
            ['cuenta' => 1, 'description' => 'ACTIVO', 'tipocuenta' => 'T', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 101, 'description' => 'ACTIVO CORRIENTE', 'tipocuenta' => 'T', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 10101, 'description' => 'EFECTIVO Y EQUIVALENTES AL EFECTIVO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 10102, 'description' => 'ACTIVOS FINANCIEROS', 'tipocuenta' => 'T', 'signo' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1010201, 'description' => 'ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010202, 'description' => 'ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010203, 'description' => 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010204, 'description' => '(-) PROVISION POR DETERIORO', 'tipocuenta' => 'D', 'signo' => 'N', 'tipoestado' => 1],
            ['cuenta' => 1010205, 'description' => 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES NO RELACIONADOS', 'tipocuenta' => 'T', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 101020501, 'description' => 'DE ACTIVIDADES ORDINARIAS QUE GENEREN INTERESES', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 101020502, 'description' => 'DE ACTIVIDADES ORDINARIAS QUE NO GENEREN INTERESES', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010206, 'description' => 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES RELACIONADOS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010207, 'description' => 'OTRAS CUENTAS POR COBRAR RELACIONADAS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010208, 'description' => 'OTRAS CUENTAS POR COBRAR', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010209, 'description' => '(-) PROVISIÓN CUENTAS INCOBRABLES Y DETERIORO', 'tipocuenta' => 'D', 'signo' => 'N', 'tipoestado' => 1],
            ['cuenta' => 10103, 'description' => 'INVENTARIOS', 'tipocuenta' => 'T', 'signo' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1010301, 'description' => 'INVENTARIOS DE MATERIA PRIMA', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010302, 'description' => 'INVENTARIOS DE PRODUCTOS EN PROCESO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010303, 'description' => 'INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN EL PROCESO DE PRODUCCIÓN', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010304, 'description' => 'INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN LA PRESTACIÓN DE SERVICIO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010305, 'description' => 'INVENTARIOS DE PRODUCTOS TERMINADOS Y MERCADERIA EN ALMACÉN - PRODUCIDO POR LA COMPAÑÍA', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010306, 'description' => 'INVENTARIOS DE PRODUCTOS TERMINADOS Y MERCADERIA EN ALMACÉN - COMPRADO DE TERCEROS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010307, 'description' => 'MERCADERÍAS EN TRÁNSITO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010308, 'description' => 'OBRAS EN CONSTRUCCION', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010309, 'description' => 'OBRAS TERMINADAS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010310, 'description' => 'MATERIALES O BIENES PARA LA CONSTRUCCIÓN', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            //Pag2
            ['cuenta' => 1010311, 'description' => 'INVENTARIOS REPUESTOS, HERRAMIENTAS Y ACCESORIOS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010312, 'description' => 'OTROS INVENTARIOS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010313, 'description' => '(-) PROVISIÓN POR VALOR NETO DE REALIZACIÓN Y OTRAS PÉRDIDAS EN EL INVENTARIO', 'tipocuenta' => 'D', 'signo' => 'N', 'tipoestado' => 1],
            ['cuenta' => 10104, 'description' => 'SERVICIOS Y OTROS PAGOS ANTICIPADOS', 'tipocuenta' => 'T', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010401, 'description' => 'SEGUROS PAGADOS POR ANTICIPADO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010402, 'description' => 'ARRIENDOS PAGADOS POR ANTICIPADO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010403, 'description' => 'ANTICIPOS A PROVEEDORES', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010404, 'description' => 'OTROS ANTICIPOS ENTREGADOS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 10105, 'description' => 'ACTIVOS POR IMPUESTOS CORRIENTES', 'tipocuenta' => 'T', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010501, 'description' => 'CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA (IVA)', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010502, 'description' => 'CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA (I. R.)', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010503, 'description' => 'OTROS CRÉDITOS TRIBUTARIOS A FAVOR DE LA EMPRESA', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1010504, 'description' => 'PROVISIÓN PARA IMPUESTOS', 'tipocuenta' => 'D', 'signo' => 'N', 'tipoestado' => 1],
            ['cuenta' => 102, 'description' => 'ACTIVO NO CORRIENTE', 'tipocuenta' => 'T', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 10201, 'description' => 'PROPIEDADES, PLANTA Y EQUIPO', 'tipocuenta' => 'T', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1020101, 'description' => 'TERRENOS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1020102, 'description' => 'EDIFICIOS', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1020103, 'description' => 'CONSTRUCCIONES EN CURSO', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1020104, 'description' => 'INSTALACIONES', 'tipocuenta' => 'D', 'signo' => 'P', 'tipoestado' => 1],
            ['cuenta' => 1020105, 'description' => 'MUEBLES Y ENSERES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020106, 'description' => 'MAQUINARIA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020107, 'description' => 'NAVES, AERONAVES, BARCAZAS Y SIMILARES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020108, 'description' => 'EQUIPO DE COMPUTACIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020109, 'description' => 'VEHÍCULOS, EQUIPOS DE TRANSPORTE Y EQUIPO CAMINERO MÓVIL', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020110, 'description' => 'OTROS PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020111, 'description' => 'REPUESTOS Y HERRAMIENTAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020112, 'description' => '(-) DEPRECIACIÓN ACUMULADA PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020113, 'description' => '(-) DETERIORO ACUMULADO DE PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020114, 'description' => 'ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 10201401, 'description' => 'ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10201402, 'description' => '(-) AMORTIZACIÓN ACUMULADA DE ACTIVOS DE EXLORACIÓN Y EXPLOTACIÓN', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10201403, 'description' => '(-) DETERIORO ACUMULADO DE ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10202, 'description' => 'PROPIEDADES DE INVERSIÓN', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 1020201, 'description' => 'TERRENOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020202, 'description' => 'EDIFICIOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020203, 'description' => '(-) DEPRECIACION ACUMULADA DE PROPIEDADES DE INVERSIÓN', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],

            //PAG 3
            ['cuenta' => 1020204, 'description' => '(-) DETERIORO ACUMULADO DE PROPIEDADES DE INVERSIÓN', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10203, 'description' => 'ACTIVOS BIOLOGICOS', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 1020301, 'description' => 'ANIMALES VIVOS EN CRECIMIENTO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020302, 'description' => 'ANIMALES VIVOS EN PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020303, 'description' => 'PLANTAS EN CRECIMIENTO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020304, 'description' => 'PLANTAS EN PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020305, 'description' => '(-) DEPRECIACIÓN ACUMULADA DE ACTIVOS BIOLÓGICOS', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020306, 'description' => '(-) DETERIORO ACUMULADO DE ACTIVOS BIOLÓGICOS', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10204, 'description' => 'ACTIVO INTANGIBLE', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 1020401, 'description' => 'PLUSVALÍAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020402, 'description' => 'MARCAS, PATENTES, DERECHOS DE LLAVE, CUOTAS PATRIMONIALES Y OTROS SIMILARES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020403, 'description' => 'ACTIVOS DE EXPLORACION Y EXPLOTACION', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020404, 'description' => '(-) AMORTIZACIÓN ACUMULADA DE ACTIVO INTANGIBLE', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020405, 'description' => '(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020406, 'description' => 'OTROS INTANGIBLES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10205, 'description' => 'ACTIVOS POR IMPUESTOS DIFERIDOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10206, 'description' => 'ACTIVOS FINANCIEROS NO CORRIENTES', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 1020601, 'description' => 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020602, 'description' => '(-) PROVISIÓN POR DETERIORO DE ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020603, 'description' => 'DOCUMENTOS Y CUENTAS POR COBRAR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020604, 'description' => '(-) PROVISIÓN CUENTAS INCOBRABLES DE ACTIVOS FINANCIEROS NO CORRIENTES', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 10207, 'description' => 'OTROS ACTIVOS NO CORRIENTES', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 1020701, 'description' => 'INVERSIONES SUBSIDIARIAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020702, 'description' => 'INVERSIONES ASOCIADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020703, 'description' => 'INVERSIONES NEGOCIOS CONJUNTOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020704, 'description' => 'OTRAS INVERSIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020705, 'description' => '(-) PROVISIÓN VALUACIÓN DE INVERSIONES', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1020706, 'description' => 'OTROS ACTIVOS NO CORRIENTES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2, 'description' => 'PASIVO', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 201, 'description' => 'PASIVO CORRIENTE', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 20101, 'description' => 'PASIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20102, 'description' => 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIEROS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20103, 'description' => 'CUENTAS Y DOCUMENTOS POR PAGAR', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2010301, 'description' => 'LOCALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2010302, 'description' => 'DEL EXTERIOR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20104, 'description' => 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2010401, 'description' => 'LOCALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            //Pag4
            ['cuenta' => 2010402, 'description' => 'DEL EXTERIOR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20105, 'description' => 'PROVISIONES', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2010501, 'description' => 'LOCALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2010502, 'description' => 'DEL EXTERIOR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20106, 'description' => 'PORCIÓN CORRIENTE DE OBLIGACIONES EMITIDAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20107, 'description' => 'OTRAS OBLIGACIONES CORRIENTES', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2010701, 'description' => 'CON LA ADMINISTRACIÓN TRIBUTARIA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2010702, 'description' => 'IMPUESTO A LA RENTA POR PAGAR DEL EJERCICIO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2010703, 'description' => 'CON EL IESS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2010704, 'description' => 'POR BENEFICIOS DE LEY A EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2010705, 'description' => 'PARTICIPACIÓN TRABAJADORES POR PAGAR DEL EJERCICIO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2010706, 'description' => 'DIVIDENDOS POR PAGAR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20108, 'description' => 'CUENTAS POR PAGAR DIVERSAS – RELACIONADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20109, 'description' => 'OTROS PASIVOS FINANCIEROS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20110, 'description' => 'ANTICIPOS DE CLIENTES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20111, 'description' => 'PASIVOS DIRECTAMENTE ASOCIADOS CON LOS ACTIVOS NO CORRIENTES Y OPERACIONES DISCONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20112, 'description' => 'PORCIÓN CORRIENTE DE PROVISIONES POR BENEFICIOS A EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2011201, 'description' => 'JUBILACIÓN PATRONAL', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2011202, 'description' => 'OTROS BENEFICIOS A LARGO PLAZO PARA LOS EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20113, 'description' => 'OTROS PASIVOS CORRIENTES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 202, 'description' => 'PASIVO NO CORRIENTE', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 20201, 'description' => 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIERO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20202, 'description' => 'CUENTAS Y DOCUMENTOS POR PAGAR', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2020201, 'description' => 'LOCALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2020202, 'description' => 'DEL EXTERIOR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20203, 'description' => 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2020301, 'description' => 'LOCALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2020302, 'description' => 'DEL EXTERIOR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20204, 'description' => 'CUENTAS POR PAGAR DIVERSAS / RELACIONADAS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2020401, 'description' => 'LOCALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2020402, 'description' => 'DEL EXTERIOR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20205, 'description' => 'OBLIGACIONES EMITIDAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20206, 'description' => 'ANTICIPOS DE CLIENTES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20207, 'description' => 'PROVISIONES POR BENEFICIOS A EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 2020701, 'description' => 'JUBILACIÓN PATRONAL', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2020702, 'description' => 'OTROS BENEFICIOS NO CORRIENTES PARA LOS EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20208, 'description' => 'OTRAS PROVISIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20209, 'description' => 'PASIVO DIFERIDO', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            //Pag5
            ['cuenta' => 2020901, 'description' => 'INGRESOS DIFERIDOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2020902, 'description' => 'PASIVOS POR IMPUESTOS DIFERIDOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 20210, 'description' => 'OTROS PASIVOS NO CORRIENTES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 3, 'description' => 'PATRIMONIO NETO', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 30, 'description' => 'PATRIMONIO ATRIBUIBLE A LOS PROPIETARIOS DE LA CONTROLADORA', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 301, 'description' => 'CAPITAL', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 30101, 'description' => 'CAPITAL SUSCRITO o ASIGNADO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30102, 'description' => '(-) CAPITAL SUSCRITO NO PAGADO, ACCIONES EN TESORERÍA', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 302, 'description' => 'APORTES DE SOCIOS O ACCIONISTAS PARA FUTURA CAPITALIZACIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 303, 'description' => 'PRIMA POR EMISION PRIMARIA DE ACCIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 304, 'description' => 'RESERVAS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 30401, 'description' => 'RESERVA LEGAL', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30402, 'description' => 'RESERVAS FACULTATIVA Y ESTATUTARIA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 305, 'description' => 'OTROS RESULTADOS INTEGRALES', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 30501, 'description' => 'SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30502, 'description' => 'SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30503, 'description' => 'SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30504, 'description' => 'OTROS SUPERAVIT POR REVALUACION', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 306, 'description' => 'RESULTADOS ACUMULADOS', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 30601, 'description' => 'GANACIAS ACUMULADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30602, 'description' => '(-) PÉRDIDAS ACUMULADAS', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30603, 'description' => 'RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPCIÓN POR PRIMERA VEZ DE LAS NIIF', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30604, 'description' => 'RESERVA DE CAPITAL', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30605, 'description' => 'RESERVA POR DONACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30606, 'description' => 'RESERVA POR VALUACIÓN', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30607, 'description' => 'SUPERÁVIT POR REVALUACIÓN DE INVERSIONES', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 307, 'description' => 'RESULTADOS DEL EJERCICIO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 30701, 'description' => 'GANANCIA NETA DEL PERIODO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 30702, 'description' => '(-) PÉRDIDA NETA DEL PERIODO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 31, 'description' => 'PARTICIPACIÓN NO CONTROLADORA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 41, 'description' => 'INGRESOS DE ACTIVIDADES ORDINARIAS', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 4101, 'description' => 'VENTA DE BIENES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4102, 'description' => 'PRESTACIÓN DE SERVICIOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4103, 'description' => 'CONTRATOS DE CONSTRUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4104, 'description' => 'SUBVENCIONES DEL GOBIERNO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4105, 'description' => 'REGALÍAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            //pag6
            ['cuenta' => 4106, 'description' => 'INTERESES', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 410601, 'description' => 'INTERESES GENERADOS POR VENTAS A CRÉDITO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 410602, 'description' => 'OTROS INTERESES GENERADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4107, 'description' => 'DIVIDENDOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4108, 'description' => 'GANANCIA POR MEDICIÓN A VALOR RAZONABLE DE ACTIVOS BIOLÓGICOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4109, 'description' => 'OTROS INGRESOS DE ACTIVIDADES ORDINARIAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4110, 'description' => '(-) DESCUENTO EN VENTAS', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4111, 'description' => '(-) DEVOLUCIONES EN VENTAS', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4112, 'description' => '(-) BONIFICACIÓN EN PRODUCTO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4113, 'description' => '(-) OTRAS REBAJAS COMERCIALES', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 42, 'description' => 'GANANCIA BRUTA --> Subtotal A (41 - 51)', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 43, 'description' => 'OTROS INGRESOS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 4301, 'description' => 'DIVIDENDOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4302, 'description' => 'INTERESES FINANCIEROS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4303, 'description' => 'GANANCIA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4304, 'description' => 'VALUACIÓN DE INSTRUMENTOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN RESULTADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4305, 'description' => 'OTRAS RENTAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 51, 'description' => 'COSTO DE VENTAS Y PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 5101, 'description' => 'MATERIALES UTILIZADOS O PRODUCTOS VENDIDOS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 510101, 'description' => '(+) INVENTARIO INICIAL DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510102, 'description' => '(+) COMPRAS NETAS LOCALES DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510103, 'description' => '(+) IMPORTACIONES DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510104, 'description' => '(-) INVENTARIO FINAL DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510105, 'description' => '(+) INVENTARIO INICIAL DE MATERIA PRIMA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510106, 'description' => '(+) COMPRAS NETAS LOCALES DE MATERIA PRIMA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510107, 'description' => '(+) IMPORTACIONES DE MATERIA PRIMA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510108, 'description' => '(-) INVENTARIO FINAL DE MATERIA PRIMA', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510109, 'description' => '(+) INVENTARIO INICIAL DE PRODUCTOS EN PROCESO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510110, 'description' => '(-) INVENTARIO FINAL DE PRODUCTOS EN PROCESO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510111, 'description' => '(+) INVENTARIO INICIAL PRODUCTOS TERMINADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510112, 'description' => '(-) INVENTARIO FINAL DE PRODUCTOS TERMINADOS', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5102, 'description' => '(+) MANO DE OBRA DIRECTA', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 510201, 'description' => 'SUELDOS Y BENEFICIOS SOCIALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510202, 'description' => 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5103, 'description' => '(+) MANO DE OBRA INDIRECTA', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 510301, 'description' => 'SUELDOS Y BENEFICIOS SOCIALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510302, 'description' => 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5104, 'description' => '(+) OTROS COSTOS INDIRECTOS DE FABRICACIÓN', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            //pag7
            ['cuenta' => 510401, 'description' => 'DEPRECIACIÓN PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510402, 'description' => 'DETERIORO O PÉRDIDAS DE ACTIVOS BIOLÓGICOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510403, 'description' => 'DETERIORO DE PROPIEDAD, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510404, 'description' => 'EFECTO VALOR NETO DE REALIZACIÓN DE INVENTARIOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510405, 'description' => 'GASTO POR GARANTÍAS EN VENTA DE PRODUCTOS O SERVICIOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510406, 'description' => 'MANTENIMIENTO Y REPARACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510407, 'description' => 'SUMINISTROS MATERIALES Y REPUESTOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 510408, 'description' => 'OTROS COSTOS DE PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 5201, 'description' => 'GASTOS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 520102, 'description' => 'SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520103, 'description' => 'APORTES A LA SEGURIDAD SOCIAL (incluido fondo de reserva)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520104, 'description' => 'BENEFICIOS SOCIALES E INDEMNIZACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520105, 'description' => 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520106, 'description' => 'HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520107, 'description' => 'REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520108, 'description' => 'HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520109, 'description' => 'MANTENIMIENTO Y REPARACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520110, 'description' => 'ARRENDAMIENTO OPERATIVO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520111, 'description' => 'COMISIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520112, 'description' => 'PROMOCIÓN Y PUBLICIDAD', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520113, 'description' => 'COMBUSTIBLES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520114, 'description' => 'LUBRICANTES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520115, 'description' => 'SEGUROS Y REASEGUROS (primas y cesiones)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520116, 'description' => 'TRANSPORTE', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520117, 'description' => 'GASTOS DE GESTIÓN (agasajos a accionistas, trabajadores y clientes)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520118, 'description' => 'GASTOS DE VIAJE', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520119, 'description' => 'AGUA, ENERGÍA, LUZ Y TELECOMUNICACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520120, 'description' => 'NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012101, 'description' => 'DEPRECIACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012102, 'description' => 'PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012103, 'description' => 'PROPIEDADES DE INVERSIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012104, 'description' => 'AMORTIZACIONES', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 52012105, 'description' => 'INTANGIBLES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012106, 'description' => 'OTROS ACTIVOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012301, 'description' => 'GASTO DETERIORO', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 52012302, 'description' => 'PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            //pag8
            ['cuenta' => 52012306, 'description' => 'OTROS ACTIVOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520124, 'description' => 'GASTOS POR CANTIDADES ANORMALES DE UTILIZACIÓN EN EL PROCESO DE PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 52012401, 'description' => 'MANO DE OBRA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012402, 'description' => 'MATERIALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52012403, 'description' => 'COSTOS DE PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520125, 'description' => 'GASTO POR REESTRUCTURACIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520126, 'description' => 'VALOR NETO DE REALIZACIÓN DE INVENTARIOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520128, 'description' => 'OTROS GASTOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202, 'description' => 'GASTOS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 520201, 'description' => 'SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520202, 'description' => 'APORTES A LA SEGURIDAD SOCIAL (incluido fondo de reserva)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520203, 'description' => 'BENEFICIOS SOCIALES E INDEMNIZACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520204, 'description' => 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520205, 'description' => 'HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520206, 'description' => 'REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520207, 'description' => 'HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520208, 'description' => 'MANTENIMIENTO Y REPARACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520209, 'description' => 'ARRENDAMIENTO OPERATIVO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520210, 'description' => 'COMISIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520212, 'description' => 'COMBUSTIBLES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520213, 'description' => 'LUBRICANTES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520214, 'description' => 'SEGUROS Y REASEGUROS (primas y cesiones)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520215, 'description' => 'TRANSPORTE', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520216, 'description' => 'GASTOS DE GESTIÓN (agasajos a accionistas, trabajadores y clientes)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520217, 'description' => 'GASTOS DE VIAJE', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520218, 'description' => 'AGUA, ENERGÍA, LUZ Y TELECOMUNICACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520219, 'description' => 'NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520220, 'description' => 'IMPUESTOS, CONTRIBUCIONES Y OTROS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520221, 'description' => 'DEPRECIACIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52022101, 'description' => 'PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52022102, 'description' => 'PROPIEDADES DE INVERSIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520222, 'description' => 'AMORTIZACIONES', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            //Pag9
            ['cuenta' => 52022201, 'description' => 'INTANGIBLES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 52022202, 'description' => 'OTROS ACTIVOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520223, 'description' => 'GASTO DETERIORO', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 5202301, 'description' => 'PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202302, 'description' => 'INVENTARIOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202303, 'description' => 'INSTRUMENTOS FINANCIEROS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202404, 'description' => 'INTANGIBLES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202315, 'description' => 'CUENTAS POR COBRAR', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202326, 'description' => 'OTROS ACTIVOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520124, 'description' => 'GASTOS POR CANTIDADES ANORMALES DE UTILIZACIÓN EN EL PROCESO DE PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 5202401, 'description' => 'MANO DE OBRA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202402, 'description' => 'MATERIALES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5202403, 'description' => 'COSTOS DE PRODUCCIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520225, 'description' => 'GASTO POR REESTRUCTURACIÓN', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520226, 'description' => 'VALOR NETO DE REALIZACIÓN DE INVENTARIOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520227, 'description' => 'GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS DIFERIDOS)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520228, 'description' => 'OTROS GASTOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5203, 'description' => 'GASTOS FINANCIEROS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 520301, 'description' => 'INTERESES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520302, 'description' => 'COMISIONES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520303, 'description' => 'GASTOS DE FINANCIAMIENTO DE ACTIVOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520304, 'description' => 'DIFERENCIA EN CAMBIO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520305, 'description' => 'OTROS GASTOS FINANCIEROS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5204, 'description' => 'OTROS GASTOS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 520401, 'description' => 'PERDIDA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 520402, 'description' => 'OTROS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 60, 'description' => 'GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA DE OPERACIONES CONTINUADAS --> Subtotal B (A + 43 - 52)', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 61, 'description' => '15% PARTICIPACIÓN TRABAJADORES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 62, 'description' => 'GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS --> Subtotal C (B - 61)', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 63, 'description' => 'IMPUESTO A LA RENTA CAUSADO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 64, 'description' => 'GANANCIA (PÉRDIDA) DE OPERACIONES CONTINUADAS ANTES DEL IMPUESTO DIFERIDO --> Subtotal D (C - 63)', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 65, 'description' => '(-) GASTO POR IMPUESTO DIFERIDO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 66, 'description' => '(+) INGRESO POR IMPUESTO DIFERIDO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 67, 'description' => 'GANANCIA (PÉRDIDA) DE OPERACIONES CONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 71, 'description' => 'INGRESOS POR OPERACIONES DESCONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 72, 'description' => 'GASTOS POR OPERACIONES DESCONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 73, 'description' => 'GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA DE OPERACIONES DESCONTINUADAS --> Subtotal E (71 - 72)', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 74, 'description' => '15% PARTICIPACIÓN TRABAJADORES', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            //pag10
            ['cuenta' => 75, 'description' => 'GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS DE OPERACIONES DISCONTINUADAS --> Subtotal F (E - 74)', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 76, 'description' => 'IMPUESTO A LA RENTA CAUSADO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 77, 'description' => 'GANANCIA (PÉRDIDA) DE OPERACIONES DISCONTINUADAS --> Subtotal G (F - 76)', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 79, 'description' => 'GANANCIA (PÉRDIDA) NETA DEL PERIODO --> Subtotal H (D + G)', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 7901, 'description' => 'PROPIETARIOS DE LA CONTROLADORA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 7902, 'description' => 'PARTICIPACIÓN ATRIBUIBLE A LA NO CONTROLADORA (informativo)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 81, 'description' => 'COMPONENTES DEL OTRO RESULTADO INTEGRAL', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 8101, 'description' => 'DIFERENCIA DE CAMBIO POR CONVERSIÓN', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8102, 'description' => 'VALUACIÓN DE ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8103, 'description' => 'GANANCIAS POR REVALUACIÓN DE PROPIEDADES, PLANTA Y EQUIPO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8104, 'description' => 'GANANCIAS (PÉRDIDAS) ACTUARIALES POR PLANES DE BENEFICIOS DEFINIDOS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8105, 'description' => 'REVERSIÓN DEL DETERIORO (PÉRDIDA POR DETERIORO) DE UN ACTIVO REVALUADO', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8106, 'description' => 'PARTICIPACIÓN DE OTRO RESULTADO INTEGRAL DE ASOCIADAS', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8107, 'description' => 'IMPUESTO SOBRE LAS GANANCIAS RELATIVO A OTRO RESULTADO INTEGRAL', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8108, 'description' => 'OTROS (DETALLAR EN NOTAS)', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 82, 'description' => 'RESULTADO INTEGRAL TOTAL DEL AÑO --> Subtotal I (H + 81)', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 8201, 'description' => 'PROPIETARIOS DE LA CONTROLADORA', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 8202, 'description' => 'PARTICIPACIÓN NO CONTROLADORA (Informativo)', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 90, 'description' => 'GANANCIA POR ACCIÓN (SOLO EMPRESAS QUE COTIZAN EN BOLSA)', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 9001, 'description' => 'GANANCIA POR ACCIÓN BÁSICA', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 900101, 'description' => 'GANANCIA POR ACCIÓN BÁSICA EN OPERACIONES CONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 900102, 'description' => 'GANANCIA POR ACCIÓN BÁSICA EN OPERACIONES DISCONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 9002, 'description' => 'GANANCIA POR ACCIÓN DILUIDA', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 2],
            ['cuenta' => 900201, 'description' => 'GANANCIA POR ACCIÓN DILUIDA EN OPERACIONES CONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 900202, 'description' => 'GANANCIA POR ACCIÓN DILUIDA EN OPERACIONES DISCONTINUADAS', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 91, 'description' => 'UTILIDAD A REINVERTIR (INFORMATIVO)', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 95, 'description' => 'INCREMENTO NETO (DISMINUCIÓN) EN EL EFECTIVO Y EQUIVALENTES AL EFECTIVO, ANTES DEL EFECTO DE LOS CAMBIOS EN LA TASA DE CAMBIO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 9501, 'description' => 'FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE OPERACIÓN', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 950101, 'description' => 'CLASES DE COBROS POR ACTIVIDADES DE OPERACIÓN', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 95010101, 'description' => 'Cobros procedentes de las ventas de bienes y prestación de servicios', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 95010102, 'description' => 'Cobros procedentes de regalías, cuotas, comisiones y otros ingresos de actividades ordinarias', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 95010103, 'description' => 'Cobros procedentes de contratos mantenidos con propósitos de intermediación o para negociar', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 95010104, 'description' => 'Cobros procedentes de primas y prestaciones, anualidades y otros beneficios de pólizas suscritas', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 95010105, 'description' => 'Otros cobros por actividades de operación', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950102, 'description' => 'CLASES DE PAGOS POR ACTIVIDADES DE OPERACIÓN', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 95010201, 'description' => 'Pagos a proveedores por el suministro de bienes y servicios', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 95010202, 'description' => 'Pagos procedentes de contratos mantenidos para intermediación o para negociar', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            //pag11
            ['cuenta' => 95010203, 'description' => 'Pagos a y por cuenta de los empleados', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 95010204, 'description' => 'Pagos por primas y prestaciones, anualidades y otras obligaciones derivadas de las pólizas suscritas', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 95010205, 'description' => 'Otros pagos por actividades de operación', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950103, 'description' => 'Dividendos pagados', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950104, 'description' => 'Dividendos recibidos', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950105, 'description' => 'Intereses pagados', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950106, 'description' => 'Intereses recibidos', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950107, 'description' => 'Impuestos a las ganancias pagados', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950108, 'description' => 'Otras entradas (salidas) de efectivo', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9502, 'description' => 'FLUJOS DE EFECTIVOS PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE INVERSIÓN', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 950201, 'description' => 'Efectivo procedentes de la venta de acciones en subsidiarias u otros negocios', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950202, 'description' => 'Efectivo utilizado para adquirir acciones en subsidiarias u otros negocios para tener el control', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950203, 'description' => 'Efectivo utilizado en la compra de participaciones no controladoras', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950204, 'description' => 'Otros cobros por la venta de acciones o instrumentos de deuda de otras entidades', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950205, 'description' => 'Otros pagos para adquirir acciones o instrumentos de deuda de otras entidades', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950206, 'description' => 'Otros cobros por la venta de participaciones en negocios conjuntos', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950207, 'description' => 'Otros pagos para adquirir participaciones en negocios conjuntos', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950208, 'description' => 'Importes procedentes por la venta de propiedades, planta y equipo', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950209, 'description' => 'Adquisiciones de propiedades, planta y equipo', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950210, 'description' => 'Importes procedentes de ventas de activos intangibles', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950211, 'description' => 'Compras de activos intangibles', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950212, 'description' => 'Importes procedentes de otros activos a largo plazo', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950213, 'description' => 'Compras de otros activos a largo plazo', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950214, 'description' => 'Importes procedentes de subvenciones del gobierno', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950215, 'description' => 'Anticipos de efectivo efectuados a terceros', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950216, 'description' => 'Cobros procedentes del reembolso de anticipos y préstamos concedidos a terceros', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950217, 'description' => 'Pagos derivados de contratos de futuro, a término, de opciones y de permuta financiera', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950218, 'description' => 'Cobros procedentes de contratos de futuro, a término, de opciones y de permuta financiera', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950219, 'description' => 'Dividendos recibidos', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950220, 'description' => 'Intereses recibidos', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950221, 'description' => 'Otras entradas (salidas) de efectivo', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9503, 'description' => 'FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE FINANCIACIÓN', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 950301, 'description' => 'Aporte en efectivo por aumento de capital', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950302, 'description' => 'Financiamiento por emisión de títulos valores', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950303, 'description' => 'Pagos por adquirir o rescatar las acciones de la entidad', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950304, 'description' => 'Financiación por préstamos a largo plazo', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950305, 'description' => 'Pagos de préstamos', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950306, 'description' => 'Pagos de pasivos por arrendamientos financieros', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            //pag12
            ['cuenta' => 950307, 'description' => 'Importes procedentes de subvenciones del gobierno', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950308, 'description' => 'Dividendos pagados', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950309, 'description' => 'Intereses recibidos', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 950310, 'description' => 'Otras entradas (salidas) de efectivo', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9504, 'description' => 'EFECTOS DE LA VARIACIÓN EN LA TASA DE CAMBIO SOBRE EL EFECTIVO Y EQUIVALENTES AL EFECTIVO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 950401, 'description' => 'Efectos de la variación en la tasa de cambio sobre el efectivo y equivalentes de efectivo', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9505, 'description' => 'INCREMENTO (DISMINUCIÓN) NETO DE EFECTIVO Y EQUIVALENTES AL EFECTIVO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 9506, 'description' => 'EFECTIVO Y EQUIVALENTES AL EFECTIVO AL PRINCIPIO DEL PERIODO', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9507, 'description' => 'EFECTIVO Y EQUIVALENTES AL EFECTIVO AL FINAL DEL PERIODO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 96, 'description' => 'GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 97, 'description' => 'AJUSTE POR PARTIDAS DISTINTAS AL EFECTIVO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 9701, 'description' => 'Ajustes por gasto de depreciación y amortización', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9702, 'description' => 'Ajustes por gastos por deterioro (reversiones por deterioro) reconocidas en los resultados del periodo', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9703, 'description' => 'Pérdida (ganancia) de moneda extranjera no realizada', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9704, 'description' => 'Pérdidas en cambio de moneda extranjera', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9705, 'description' => 'Ajustes por gastos en provisiones', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9706, 'description' => 'Ajuste por participaciones no controladoras', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9707, 'description' => 'Ajuste por pagos basados en acciones', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9708, 'description' => 'Ajustes por ganancias (pérdidas) en valor razonable', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9709, 'description' => 'Ajustes por gasto por impuesto a la renta', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9710, 'description' => 'Ajustes por gasto por participación trabajadores', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9711, 'description' => 'Otros ajustes por partidas distintas al efectivo', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 98, 'description' => 'CAMBIOS EN ACTIVOS Y PASIVOS', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 9801, 'description' => '(Incremento) disminución en cuentas por cobrar clientes', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9802, 'description' => '(Incremento) disminución en otras cuentas por cobrar', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9803, 'description' => '(Incremento) disminución en anticipos de proveedores', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9804, 'description' => '(Incremento) disminución en inventarios', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9805, 'description' => '(Incremento) disminución en otros activos', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9806, 'description' => 'Incremento (disminución) en cuentas por pagar comerciales', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9807, 'description' => 'Incremento (disminución) en otras cuentas por pagar', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9808, 'description' => 'Incremento (disminución) en beneficios empleados', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9809, 'description' => 'Incremento (disminución) en anticipos de clientes', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9810, 'description' => 'Incremento (disminución) en otros pasivos', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 3],
            ['cuenta' => 9820, 'description' => 'FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE OPERACIÓN', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 3],
            ['cuenta' => 99, 'description' => 'SALDO AL FINAL DEL PERÍODO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 5],
            ['cuenta' => 9901, 'description' => 'SALDO REEXPRESADO DEL PERIODO INMEDIATO ANTERIOR', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 5],
            ['cuenta' => 990101, 'description' => 'SALDO DEL PERÍODO INMEDIATO ANTERIOR', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990102, 'description' => 'CAMBIOS EN POLÍTICAS CONTABLES', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            //Pag13
            ['cuenta' => 990103, 'description' => 'CORRECCIÓN DE ERRORES', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 9902, 'description' => 'CAMBIOS DEL AÑO EN EL PATRIMONIO', 'signo' => 'D', 'tipocuenta' => 'T', 'tipoestado' => 5],
            ['cuenta' => 990201, 'description' => 'Aumento (disminución) de capital social', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990202, 'description' => 'Aportes para futuras capitalizaciones', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990203, 'description' => 'Prima por emisión primaria de acciones', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990204, 'description' => 'Dividendos', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990205, 'description' => 'Transferencia de Resultados a otras cuentas patrimoniales', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990206, 'description' => 'Realización de la Reserva por Valuación de Activos Financieros Disponibles para la venta', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990207, 'description' => 'Realización de la Reserva por Valuación de Propiedades, planta y equipo', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990208, 'description' => 'Realización de la Reserva por Valuación de Activos Intangibles', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990209, 'description' => 'Otros cambios (detallar)', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],
            ['cuenta' => 990210, 'description' => 'Resultado Integral Total del Año (Ganancia o pérdida del ejercicio)', 'signo' => 'D', 'tipocuenta' => 'D', 'tipoestado' => 5],

        ];

        foreach ($cuentas as $cuenta) {
            PlanCuentas::create(array_merge($cuenta, ['template_id' => $template->id]));
        }

        $templateContabilidadBase = Template::firstOrCreate(
            ['name' => 'ContabilidadBase'],
            ['description' => 'Plantilla de contabilidad base']
        );

        $cuentasSugeridas = [
            ['cuenta' => 1101, 'description' => 'Caja y Bancos', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1102, 'description' => 'Clientes', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1103, 'description' => 'Inventarios', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 1201, 'description' => 'Activo Fijo', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2101, 'description' => 'Proveedores', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 2201, 'description' => 'Préstamos Bancarios', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 1],
            ['cuenta' => 3101, 'description' => 'Capital Social', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 3201, 'description' => 'Utilidades Retenidas', 'signo' => 'P', 'tipocuenta' => 'T', 'tipoestado' => 1],
            ['cuenta' => 4101, 'description' => 'Ventas', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 4201, 'description' => 'Ingresos Financieros', 'signo' => 'P', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5101, 'description' => 'Gastos de Administración', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5201, 'description' => 'Gastos de Ventas', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
            ['cuenta' => 5301, 'description' => 'Gastos Financieros', 'signo' => 'N', 'tipocuenta' => 'D', 'tipoestado' => 2],
        ];

        foreach ($cuentasSugeridas as $cuenta) {
            PlanCuentas::create(array_merge($cuenta, ['template_id' => $templateContabilidadBase->id]));
        }
    }
}
